/* =============================================================
   DIGITAL RISE OS — PLATFORM DATA LAYER
   platform/shared/platform-data.js

   Default seed data. Merged with localStorage on load.
   All live mutations go via DR.store.set() → localStorage.
   ============================================================= */

window.DR_DATA = {

  /* ── Businesses ─────────────────────────────────────── */
  businesses: [{
    id: 'daycare',
    name: 'Sunshine Nursery',
    industry: 'Daycare',
    website: 'https://sunshinenursery.com',
    phone: '+1 780 555 0100',
    email: 'hello@sunshinenursery.com',
    whatsapp: '+1 780 555 0100',
    location: 'Edmonton, Alberta, Canada',
    primaryColor: '#7C3AED',
    tone: 'Warm',
    googleReviewLink: 'https://g.page/r/sunshine-nursery/review',
    logo: null,
    createdAt: '2026-01-10T09:00:00Z',
  }],

  /* ── KPIs ───────────────────────────────────────────── */
  kpis: {
    totalLeads: 127,
    aiConversations: 89,
    tasksCompleted: 312,
    bookings: 23,
    reviews: 47,
    responseTime: '8s',
    leadsGrowth: 18,
    convGrowth: 24,
    tasksGrowth: 31,
    bookingsGrowth: 12,
    reviewsGrowth: 8,
  },

  /* ── Admissions Funnel ──────────────────────────────── */
  funnel: [
    { label: 'Enquiries',     count: 127, pct: 100 },
    { label: 'Qualified',     count: 89,  pct: 70  },
    { label: 'Tours Booked',  count: 54,  pct: 43  },
    { label: 'Tours Attended',count: 38,  pct: 30  },
    { label: 'Enrolled',      count: 23,  pct: 18  },
  ],

  /* ── Lead Sources ───────────────────────────────────── */
  leadSources: [
    { label: 'Website AI Chat', pct: 52, color: '#7C3AED' },
    { label: 'WhatsApp',        pct: 21, color: '#25D366' },
    { label: 'Google Search',   pct: 14, color: '#4285F4' },
    { label: 'Phone',           pct: 8,  color: '#F59E0B' },
    { label: 'Facebook',        pct: 5,  color: '#1877F2' },
  ],

  /* ── Weekly Enquiries ───────────────────────────────── */
  weeklyEnquiries: [
    { day: 'Mon', count: 14 },
    { day: 'Tue', count: 22 },
    { day: 'Wed', count: 18 },
    { day: 'Thu', count: 27 },
    { day: 'Fri', count: 19 },
    { day: 'Sat', count: 8  },
    { day: 'Sun', count: 5  },
  ],

  /* ── Activity Feed ──────────────────────────────────── */
  activityFeed: [
    { id: 1, type: 'tour',     icon: 'calendar', color: 'purple', msg: 'Ava booked a tour for <strong>Sarah Mitchell</strong> — Thursday 10:00 AM', time: '2 min ago' },
    { id: 2, type: 'lead',     icon: 'user',     color: 'green',  msg: 'New high-intent lead: <strong>Priya Sharma</strong> — 3yr, September', time: '5 min ago' },
    { id: 3, type: 'whatsapp', icon: 'wa',       color: 'teal',   msg: 'WhatsApp confirmation sent to <strong>James Cooper</strong>', time: '8 min ago' },
    { id: 4, type: 'crm',      icon: 'db',       color: 'blue',   msg: 'CRM lead created: <strong>Emma Thompson</strong> — Callback at 2pm', time: '12 min ago' },
    { id: 5, type: 'review',   icon: 'star',     color: 'amber',  msg: 'Review request sent to <strong>Rachel Nguyen</strong> after attended tour', time: '18 min ago' },
    { id: 6, type: 'faq',      icon: 'brain',    color: 'blue',   msg: 'Maya answered 3 parent FAQs — opening hours, meals, safety', time: '25 min ago' },
    { id: 7, type: 'waitlist', icon: 'list',     color: 'orange', msg: 'Waitlist entry created: <strong>Daniel Park</strong> — 2yr, January', time: '31 min ago' },
    { id: 8, type: 'staff',    icon: 'bell',     color: 'amber',  msg: 'Staff notified — negative feedback flagged privately', time: '45 min ago' },
  ],

  /* ── AI Employees ───────────────────────────────────── */
  aiEmployees: [
    {
      id: 'ava',
      name: 'Ava',
      role: 'Admissions AI Employee',
      personality: 'Warm',
      status: 'active',
      greeting: "Hi! 👋 I'm Ava, Sunshine Nursery's AI. I can help with tours, availability, fees, and more. What can I help you with today?",
      channels: ['Website Chat', 'WhatsApp'],
      services: ['Book a Daycare Tour', 'Check Availability', 'Ask About Fees', 'Join Waiting List', 'Request Callback'],
      escalationRule: 'Escalate to human if parent is upset or question cannot be answered after 2 attempts',
      languages: ['English'],
      stats: { tasksCompleted: 234, accuracy: 97, avgResponseTime: '8s', leadsCreated: 89 },
    },
    {
      id: 'maya',
      name: 'Maya',
      role: 'Parent Support AI Employee',
      personality: 'Professional',
      status: 'active',
      greeting: "Hello! I'm Maya. I'm here to answer any questions you have about Sunshine Nursery. How can I help?",
      channels: ['Website Chat', 'Email'],
      services: ['Parent FAQ', 'Existing Parent Support'],
      escalationRule: 'Escalate immediately if parent mentions safeguarding or an incident',
      languages: ['English'],
      stats: { tasksCompleted: 68, accuracy: 99, avgResponseTime: '5s', leadsCreated: 12 },
    },
    {
      id: 'nova',
      name: 'Nova',
      role: 'Review AI Employee',
      personality: 'Friendly',
      status: 'active',
      greeting: "Hi there! 😊 Thank you for visiting Sunshine Nursery. How was your experience with us?",
      channels: ['WhatsApp', 'Email'],
      services: ['Review Management'],
      escalationRule: 'If negative feedback: create private staff task immediately',
      languages: ['English'],
      stats: { tasksCompleted: 10, accuracy: 100, avgResponseTime: '12s', leadsCreated: 2 },
    },
  ],

  /* ── CRM Leads ──────────────────────────────────────── */
  leads: [
    {
      id: 'lead-1',
      parentName: 'Sarah Mitchell',
      childAge: '3 years',
      service: 'Book a Daycare Tour',
      status: 'Tour Booked',
      statusColor: 'green',
      source: 'Website AI Chat',
      nextAction: 'Tour — Thursday 10:00 AM',
      assignedTo: 'Ava (AI)',
      lastActivity: '2 min ago',
      phone: '780-555-0198',
      email: 'sarah.mitchell@email.com',
      careType: 'Full-time',
      startDate: 'September 2026',
      tourDate: 'Thursday 10:00 AM',
      notes: 'Very interested. 3-year-old daughter. Full-time from September.',
      aiActions: ['Lead captured', 'Parent qualified', 'Tour booked', 'WhatsApp sent', 'CRM created', 'Staff notified', 'Reminder scheduled'],
      conversationId: 'conv-1',
    },
    {
      id: 'lead-2',
      parentName: 'James Cooper',
      childAge: '2 years',
      service: 'Join Waiting List',
      status: 'Waitlisted',
      statusColor: 'orange',
      source: 'Website AI Chat',
      nextAction: 'Monthly update scheduled',
      assignedTo: 'Ava (AI)',
      lastActivity: '8 min ago',
      phone: '07891 234567',
      email: 'james.cooper@email.com',
      careType: 'Full-time',
      startDate: 'January 2026',
      tourDate: null,
      notes: '2-year-old son. Waitlist January. Full-time.',
      aiActions: ['Lead captured', 'No space noted', 'Waitlist created', 'Monthly follow-up set', 'Staff notified'],
      conversationId: 'conv-2',
    },
    {
      id: 'lead-3',
      parentName: 'Emma Thompson',
      childAge: '4 years',
      service: 'Request Callback',
      status: 'Callback Scheduled',
      statusColor: 'purple',
      source: 'WhatsApp',
      nextAction: 'Call — Today 2:00 PM',
      assignedTo: 'Admissions Manager',
      lastActivity: '12 min ago',
      phone: '07700 900123',
      email: 'emma.thompson@email.com',
      careType: 'Part-time',
      startDate: 'October 2026',
      tourDate: null,
      notes: 'Interested in part-time. Prefers afternoon call.',
      aiActions: ['Callback requested', 'Time confirmed', 'Staff task created', 'WhatsApp reminder set', 'CRM updated'],
      conversationId: 'conv-3',
    },
    {
      id: 'lead-4',
      parentName: 'Priya Sharma',
      childAge: '1 year',
      service: 'Check Availability',
      status: 'High-Intent Lead',
      statusColor: 'blue',
      source: 'Google Search',
      nextAction: 'Tour reserved — Wed 10:00 AM',
      assignedTo: 'Ava (AI)',
      lastActivity: '18 min ago',
      phone: '+1 780 555 0292',
      email: 'priya.sharma@email.com',
      careType: 'Full-time',
      startDate: 'September 2026',
      tourDate: 'Wednesday 10:00 AM',
      notes: '1-year-old. Confirmed 2 spaces available. Tour reserved.',
      aiActions: ['Availability checked', '2 places found', 'Lead tagged high-intent', 'CRM saved', 'Follow-up in 1 hour'],
      conversationId: 'conv-4',
    },
    {
      id: 'lead-5',
      parentName: 'Rachel Nguyen',
      childAge: '3 years',
      service: 'Review Management',
      status: 'Review Sent',
      statusColor: 'amber',
      source: 'Website AI Chat',
      nextAction: 'Follow up if review posted',
      assignedTo: 'Nova (AI)',
      lastActivity: '32 min ago',
      phone: '+1 780 555 0341',
      email: 'rachel.nguyen@email.com',
      careType: 'Full-time',
      startDate: 'July 2026',
      tourDate: null,
      notes: 'Enrolled. Very happy. Left 5-star review after Google link sent.',
      aiActions: ['Positive sentiment detected', 'Thank you sent', 'Review link sent', 'Review tracked'],
      conversationId: 'conv-5',
    },
  ],

  /* ── Conversations ──────────────────────────────────── */
  conversations: [
    {
      id: 'conv-1',
      parentName: 'Sarah Mitchell',
      service: 'Book a Daycare Tour',
      channel: 'Website Chat',
      status: 'Completed',
      statusColor: 'green',
      preview: 'Tour booked for Thursday 10:00 AM — WhatsApp confirmation sent',
      time: '2 min ago',
      aiEmployee: 'Ava',
      messages: [
        { role: 'parent', text: "Hi! I'd like to book a tour of your daycare, please.", time: '09:01' },
        { role: 'ai', text: "Hi! 👋 We'd love to show you around. How old is your child, and when are you looking to start?", time: '09:01', meta: 'AI replied in 8 seconds' },
        { role: 'parent', text: "She's 3 years old. We're hoping to start in September.", time: '09:02' },
        { role: 'ai', text: "Wonderful! 🎉 We have places for 3-year-olds from September. Tours run Tuesday–Thursday. Which day works best?", time: '09:02' },
        { role: 'parent', text: "Thursday morning would be perfect, please.", time: '09:03' },
        { role: 'ai', text: "Thursday at 10:00 AM is available 📅 Could I take your name, mobile and email to confirm?", time: '09:03' },
        { role: 'parent', text: "Sarah Mitchell, 780-555-0198, sarah@email.com", time: '09:04' },
        { role: 'ai', text: "All confirmed, Sarah! 🎉 Tour booked for Thursday at 10:00 AM. WhatsApp confirmation sent to 780-555-0198.", time: '09:04', meta: 'Tour booked automatically' },
        { role: 'system', text: '✓ CRM lead created · ✓ Staff notified · ✓ 24hr reminder set · ✓ Review request prepared', time: '09:04' },
      ],
    },
    {
      id: 'conv-2',
      parentName: 'James Cooper',
      service: 'Join Waiting List',
      channel: 'Website Chat',
      status: 'Completed',
      statusColor: 'green',
      preview: 'Added to January waitlist — monthly updates scheduled',
      time: '8 min ago',
      aiEmployee: 'Ava',
      messages: [
        { role: 'parent', text: "Do you have any spaces for a 2-year-old from January?", time: '09:15' },
        { role: 'ai', text: "Hi! 👋 We're at full capacity for January for 2-year-olds, but I can add you to our waitlist. You'd be the first to know when a space opens. Interested?", time: '09:15', meta: 'AI replied in 6 seconds' },
        { role: 'parent', text: "Yes please! Full-time care needed.", time: '09:16' },
        { role: 'ai', text: "Perfect! Could I take your name, phone and email to create your waitlist entry?", time: '09:16' },
        { role: 'parent', text: "James Cooper, 07891 234567, james@email.com", time: '09:17' },
        { role: 'ai', text: "Done! ✅ James, your family is on our January waitlist for a 2-year-old full-time place. Monthly availability updates will be sent automatically. 😊", time: '09:17' },
        { role: 'system', text: '✓ Waitlist entry created · ✓ CRM added · ✓ Monthly follow-up scheduled · ✓ Staff notified', time: '09:17' },
      ],
    },
    {
      id: 'conv-3',
      parentName: 'Emma Thompson',
      service: 'Request Callback',
      channel: 'WhatsApp',
      status: 'Pending',
      statusColor: 'amber',
      preview: 'Callback scheduled for 2:00 PM — staff task created',
      time: '12 min ago',
      aiEmployee: 'Ava',
      messages: [
        { role: 'parent', text: "Hi! Can someone call me this afternoon? I have questions about part-time care.", time: '09:22' },
        { role: 'ai', text: "Of course! 😊 What time works best for you, and what's the best number to reach you on?", time: '09:22', meta: 'AI replied in 7 seconds' },
        { role: 'parent', text: "2pm today please. 07700 900123 — Emma Thompson", time: '09:23' },
        { role: 'ai', text: "All sorted, Emma! ✅ Callback confirmed at 2:00 PM. Our admissions team will call 07700 900123. WhatsApp reminder set for 1:30 PM 📞", time: '09:23' },
        { role: 'system', text: '✓ Staff task created · ✓ WhatsApp reminder set · ✓ CRM updated', time: '09:23' },
      ],
    },
    {
      id: 'conv-4',
      parentName: 'Priya Sharma',
      service: 'Check Availability',
      channel: 'Website Chat',
      status: 'In Progress',
      statusColor: 'blue',
      preview: 'Tour reserved — 2 spaces confirmed for September',
      time: '18 min ago',
      aiEmployee: 'Ava',
      messages: [
        { role: 'parent', text: "Do you have spaces for a 1-year-old from September?", time: '09:35' },
        { role: 'ai', text: "Hi! 👋 Yes — we have 2 full-time places available for 1-year-olds from September. Would you like to come and see us?", time: '09:35', meta: 'AI replied in 5 seconds' },
        { role: 'parent', text: "Yes definitely! Can I book a tour?", time: '09:36' },
        { role: 'ai', text: "Absolutely! We have Wednesday 10:00 AM available. Shall I reserve that for you?", time: '09:36' },
        { role: 'parent', text: "Wednesday 10am is perfect.", time: '09:37' },
        { role: 'ai', text: "Reserved! ✅ Wednesday at 10:00 AM. Our admissions team will be in touch to confirm. You're flagged as high-priority — we'll make sure one of those 2 spaces stays for you!", time: '09:37' },
      ],
    },
    {
      id: 'conv-5',
      parentName: 'Rachel Nguyen',
      service: 'Review Management',
      channel: 'WhatsApp',
      status: 'Completed',
      statusColor: 'green',
      preview: 'Google review link sent — 5-star review received',
      time: '32 min ago',
      aiEmployee: 'Nova',
      messages: [
        { role: 'parent', text: "We've been at Sunshine Nursery 2 months and we absolutely love it!", time: '09:48' },
        { role: 'ai', text: "That's so wonderful to hear! 😊 Thank you — it genuinely means the world to our whole team. Would you be willing to share a quick Google review? It takes under 2 minutes and helps other local families find us ⭐", time: '09:48', meta: 'Positive sentiment detected' },
        { role: 'parent', text: "Absolutely! Send me the link.", time: '09:49' },
        { role: 'ai', text: "Done! 💙 Your Google review link has been sent to your email and WhatsApp. Every review makes such a difference. Thank you, Rachel!", time: '09:49' },
        { role: 'system', text: '✓ Positive sentiment detected · ✓ Review link sent · ✓ Review request tracked in CRM', time: '09:49' },
      ],
    },
    {
      id: 'conv-6',
      parentName: 'Existing Parent',
      service: 'Parent Support',
      channel: 'Website Chat',
      status: 'Completed',
      statusColor: 'green',
      preview: 'Holiday dates confirmed — allergy flagged to key worker',
      time: '45 min ago',
      aiEmployee: 'Maya',
      messages: [
        { role: 'parent', text: "Hi! Can you tell me the Christmas closure dates?", time: '10:05' },
        { role: 'ai', text: "Hi! 👋 We close Friday 20th December at 6:30 PM and reopen Thursday 2nd January 2026. I'll email you the full annual holiday schedule now 🎄", time: '10:05', meta: 'AI replied in 5 seconds' },
        { role: 'parent', text: "Also — my daughter has a nut allergy. Can you flag that?", time: '10:06' },
        { role: 'ai', text: "Flagged immediately 🔴 I've alerted our kitchen team and your daughter's key worker. Could you confirm — is this anaphylaxis risk or a mild intolerance?", time: '10:06' },
        { role: 'parent', text: "Mild intolerance, not anaphylaxis.", time: '10:07' },
        { role: 'ai', text: "Noted — mild nut intolerance recorded on her file ✅ Our allergy management policy has been sent to your email. She's safe with us!", time: '10:07' },
        { role: 'system', text: '✓ Holiday dates confirmed · ✓ Allergy flagged to kitchen + key worker · ✓ Policy document sent · ✓ CRM updated', time: '10:07' },
      ],
    },
  ],

  /* ── Automations ────────────────────────────────────── */
  automations: [
    {
      id: 'auto-1',
      trigger: 'New parent enquiry received',
      aiAction: 'Qualify parent — collect age, care type, start date',
      businessAction: 'Create CRM lead + tag intent level',
      followUp: 'Send WhatsApp confirmation',
      status: true,
      color: 'purple',
      runsToday: 14,
      totalRuns: 412,
    },
    {
      id: 'auto-2',
      trigger: 'Tour booked',
      aiAction: 'Confirm booking details',
      businessAction: 'Create calendar entry + notify admissions team',
      followUp: 'Send WhatsApp confirmation within 60 seconds',
      status: true,
      color: 'green',
      runsToday: 5,
      totalRuns: 89,
    },
    {
      id: 'auto-3',
      trigger: '24 hours before tour',
      aiAction: 'Prepare reminder message',
      businessAction: 'Send WhatsApp reminder to parent',
      followUp: 'Log reminder sent in CRM',
      status: true,
      color: 'blue',
      runsToday: 3,
      totalRuns: 76,
    },
    {
      id: 'auto-4',
      trigger: '24 hours after tour attended',
      aiAction: 'Detect positive experience signals',
      businessAction: 'Send Google review request via WhatsApp',
      followUp: 'Track review request in CRM',
      status: true,
      color: 'amber',
      runsToday: 2,
      totalRuns: 54,
    },
    {
      id: 'auto-5',
      trigger: 'Negative feedback detected',
      aiAction: 'Acknowledge + de-escalate privately',
      businessAction: 'Create private staff follow-up task',
      followUp: 'Manager notified within 5 minutes',
      status: true,
      color: 'red',
      runsToday: 0,
      totalRuns: 7,
    },
    {
      id: 'auto-6',
      trigger: 'Waitlist enquiry received',
      aiAction: 'Add to waitlist, collect contact details',
      businessAction: 'Create CRM waitlist entry',
      followUp: 'Schedule monthly availability update',
      status: true,
      color: 'orange',
      runsToday: 4,
      totalRuns: 134,
    },
    {
      id: 'auto-7',
      trigger: 'Fee enquiry received',
      aiAction: 'Share personalised fee information',
      businessAction: 'Send brochure via email',
      followUp: 'Follow-up scheduled in 48 hours',
      status: false,
      color: 'blue',
      runsToday: 0,
      totalRuns: 67,
    },
    {
      id: 'auto-8',
      trigger: 'Existing parent support query',
      aiAction: 'Answer from knowledge base',
      businessAction: 'Log conversation + send policy doc if needed',
      followUp: 'Escalate to staff if unresolved',
      status: true,
      color: 'teal',
      runsToday: 2,
      totalRuns: 28,
    },
    {
      id: 'auto-9',
      trigger: 'Callback requested',
      aiAction: 'Collect time, topic and contact details',
      businessAction: 'Create staff task + set WhatsApp reminder',
      followUp: 'CRM updated with call outcome',
      status: true,
      color: 'indigo',
      runsToday: 1,
      totalRuns: 43,
    },
  ],

  /* ── Knowledge Base ─────────────────────────────────── */
  knowledgeBase: {
    openingHours: 'Monday to Friday, 7:30 AM to 6:30 PM. Closed on bank holidays and for two weeks over Christmas.',
    ageGroups: 'We support children from 12 months to 5 years.',
    fees: {
      fullTime: '$1,150/month — includes all meals, nappies, wipes, activities, and daily updates.',
      partTime3: '$820/month for 3 days per week.',
      partTime2: '$650/month for 2 days per week.',
      sibling: '10% sibling discount for the second child.',
      funding: 'We accept 15-hour and 30-hour Government Childcare Funding.',
    },
    meals: 'Fresh breakfast, lunch and afternoon snack prepared daily on-site. All allergies catered for. Nappies, wipes and sun cream included.',
    safety: 'All staff DBS-checked and first-aid trained. Secure keypad entry — registered adults only. Children signed in/out. Emergency contacts on file. Daily supervision logs.',
    curriculum: 'Play-based early learning: language development, fine/gross motor skills, social-emotional growth, outdoor play, music, storytelling, and creative arts. Each child has a dedicated key worker.',
    tours: 'Tours available Tuesday, Wednesday and Thursday at 10:00 AM or 2:00 PM.',
    waitlist: 'Families can join our waitlist if a room is full. Monthly availability updates sent automatically.',
    holidaySchedule: 'We follow standard public holidays and share annual closure dates in advance each January.',
    sickChildPolicy: 'Children with fever above 38°C, vomiting, diarrhoea or contagious conditions should stay home until 48 hours symptom-free. Please call by 8:30 AM if your child won\'t be in.',
    faqs: [
      { q: 'Do you provide nappies?', a: 'Yes — nappies, wipes and nappy cream are all included in the monthly fee.' },
      { q: 'What is the staff-to-child ratio?', a: '1:3 for under-2s and 1:8 for 3–5 year olds, exceeding Ofsted requirements.' },
      { q: 'Do you offer a sibling discount?', a: 'Yes — 10% off for second children enrolled at the same time.' },
      { q: 'Are you Ofsted registered?', a: 'Yes, we are fully Ofsted registered and our latest report is available on request.' },
      { q: 'Can I view the menu?', a: 'Yes — we share our seasonal menus on our parent app and at the front desk.' },
    ],
  },

  /* ── Reviews ────────────────────────────────────────── */
  reviews: {
    rating: 4.8,
    total: 47,
    breakdown: [5, 5, 4, 5, 3, 5, 5, 5, 4, 5],
    sentiment: { positive: 43, neutral: 3, negative: 1 },
    requestsSent: 54,
    conversionRate: 87,
    recent: [
      { id: 'rev-1', author: 'Rachel Nguyen', rating: 5, platform: 'Google', text: "Sunshine Nursery is absolutely wonderful. The staff are so warm and attentive — our daughter thrived from day one. Highly recommend!", time: '2 days ago', replied: false },
      { id: 'rev-2', author: 'Michael Chen', rating: 5, platform: 'Google', text: "We've been here 6 months and couldn't be happier. The curriculum is brilliant, meals are fresh, and the app keeps us updated all day. 5 stars!", time: '5 days ago', replied: true },
      { id: 'rev-3', author: 'Aisha Patel', rating: 4, platform: 'Google', text: "Really lovely nursery with caring staff. Drop-off was bumpy at first but the key worker was so patient. Would definitely recommend.", time: '1 week ago', replied: false },
      { id: 'rev-4', author: 'Anonymous', rating: 3, platform: 'Private', text: "Had a communication issue regarding holiday dates. Staff were helpful once I escalated but I wish the info had been clearer upfront.", time: '2 weeks ago', replied: true, privateNote: 'Manager spoke with parent — issue resolved. Holiday schedule updated on website.' },
    ],
  },

  /* ── Services ───────────────────────────────────────── */
  services: [
    { id: 's1', name: 'Book a Daycare Tour',       active: true },
    { id: 's2', name: 'Check Availability',         active: true },
    { id: 's3', name: 'Ask About Fees',             active: true },
    { id: 's4', name: 'Join Waiting List',           active: true },
    { id: 's5', name: 'Parent FAQ',                 active: true },
    { id: 's6', name: 'Request Callback',            active: true },
    { id: 's7', name: 'Review Management',          active: true },
    { id: 's8', name: 'Existing Parent Support',    active: true },
  ],

  /* ── Email Templates ────────────────────────────────── */
  emailTemplates: [
    { id: 'et-1', name: 'Tour Confirmation', subject: "Your Daycare Tour is Confirmed! 📅", body: "Hi {parent_name},\n\nYour tour at Sunshine Nursery is confirmed for {tour_date} at {tour_time}.\n\nOur address is {address}. Please let us know if you have any questions.\n\nLooking forward to meeting you!\n\nSunshine Nursery Team" },
    { id: 'et-2', name: 'Tour Reminder', subject: "Reminder: Your Nursery Tour is Tomorrow! 🌟", body: "Hi {parent_name},\n\nJust a friendly reminder that your tour at Sunshine Nursery is tomorrow — {tour_date} at {tour_time}.\n\nSee you then!\n\nSunshine Nursery Team" },
    { id: 'et-3', name: 'Fee Brochure', subject: "Your Sunshine Nursery Fee Guide 💛", body: "Hi {parent_name},\n\nThank you for your interest in Sunshine Nursery! Please find our fee guide and full nursery brochure attached.\n\nOur fees start from $1,150/month full-time and include all meals, activities and supplies.\n\nFeel free to book a tour — we'd love to show you around!\n\nSunshine Nursery Team" },
    { id: 'et-4', name: 'Waitlist Update', subject: "Sunshine Nursery — Waitlist Update", body: "Hi {parent_name},\n\nJust a quick monthly update on your waitlist position for {start_month}.\n\nWe currently have {waitlist_position} families ahead of you. We'll be in touch as soon as a space becomes available.\n\nThank you for your patience!\n\nSunshine Nursery Team" },
    { id: 'et-5', name: 'Review Request', subject: "Would You Leave Us a Google Review? ⭐", body: "Hi {parent_name},\n\nThank you so much for visiting Sunshine Nursery! We hope you had a wonderful experience.\n\nIf you have 2 minutes, we'd be so grateful if you could share a Google review — it really helps other local families find us:\n\n{review_link}\n\nThank you!\n\nSunshine Nursery Team" },
    { id: 'et-6', name: 'Callback Confirmation', subject: "Your Callback is Confirmed 📞", body: "Hi {parent_name},\n\nYour callback from Sunshine Nursery is confirmed for {callback_time} today.\n\nWe'll call {phone_number}. If you need to reschedule, please reply to this email.\n\nTalk soon!\n\nSunshine Nursery Team" },
  ],
};
